remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

#theme: jekyll-theme-slate

title: "COMP 232"
description: "Data Structures and Problem Solving"

hide_first_title: true
show_downloads: false
buttons:
  zip_hide: true
  tar_hide: true
  github_hide: true

github:
  is_project_page: false
